// Script para inicializar las tablas de Supabase
// Ejecutar con: npx tsx scripts/init-supabase.ts

import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://ujktxhqxhxkbrhczbhcf.supabase.co'
const serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqa3R4aHF4aGticmhjemJoY2YiLCJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzQ1OTM0MDY2LCJleHAiOjIwNjE1MTAwNjZ9.NN2UWWtaZJ2f0Y1awR9z3Rqu0c1l5KZHJ9Yw1R5P-UE'

const supabase = createClient(supabaseUrl, serviceKey)

async function createTables() {
  console.log('🔧 Creando tablas en Supabase...')
  
  // Crear tabla searches
  const { error: searchError } = await supabase.rpc('exec_sql', {
    sql: `
      CREATE TABLE IF NOT EXISTS searches (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        origin TEXT NOT NULL,
        destination TEXT NOT NULL,
        transport_mode TEXT NOT NULL,
        results JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `
  })
  
  if (searchError) {
    console.log('⚠️ Tabla searches puede que ya exista o hay error:', searchError.message)
  } else {
    console.log('✅ Tabla searches creada')
  }
  
  // Crear tabla rfqs
  const { error: rfqError } = await supabase.rpc('exec_sql', {
    sql: `
      CREATE TABLE IF NOT EXISTS rfqs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        search_query_id BIGINT,
        origin TEXT NOT NULL,
        destination TEXT NOT NULL,
        transport_mode TEXT NOT NULL,
        cargo_details TEXT,
        status TEXT DEFAULT 'pending',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `
  })
  
  if (rfqError) {
    console.log('⚠️ Tabla rfqs puede que ya exista o hay error:', rfqError.message)
  } else {
    console.log('✅ Tabla rfqs creada')
  }
  
  // Verificar tablas
  const { data: tables } = await supabase
    .from('information_schema.tables')
    .select('table_name')
    .eq('table_schema', 'public')
  
  console.log('📋 Tablas existentes:', tables?.map(t => t.table_name))
}

createTables().catch(console.error)
